[package]
name = "recursion"
description = "Implementation of the native Plonky3 recursion."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
p3-field.workspace = true
p3-mds.workspace = true
p3-symmetric.workspace = true
p3-util.workspace = true
p3-air.workspace = true
p3-matrix.workspace = true
p3-merkle-tree.workspace = true

itertools.workspace = true
rand.workspace = true
sha3.workspace = true

[dev-dependencies]
p3-baby-bear.workspace = true
p3-goldilocks.workspace = true
p3-mersenne-31.workspace = true

criterion.workspace = true
